config/routes.rb
Rails.application.routes.draw do
  resources :retrieved_articles
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  post "retrieved_articles/create_article" => "retrieved_articles#create_article", as: :create_article
  delete "retrieved_articles/delete_article", to: "retrieved_articles#delete_article", as: :delete_article

  root 'retrieved_articles#index'

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/retrieved_article.rb
class RetrievedArticle < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  protect_from_forgery with: :null_session, only: [:create_article, :destroy]

end

app/controllers/retrieved_articles_controller.rb
require "http"
require 'json'
require_relative '../services/retrieved_articles/retrieve_articles_index_request.rb'
require_relative '../services/retrieved_articles/create_article_request.rb'
require_relative '../services/retrieved_articles/destroy_article_request.rb'



class RetrievedArticlesController < ApplicationController
  #before_action :set_retrieved_article, only: %i[ show update ]
  skip_before_action :verify_authenticity_token



  # GET /retrieved_articles/1
  def show
    render json: @retrieved_article
  end


  # PATCH/PUT /retrieved_articles/1
  def update
    if @retrieved_article.update(retrieved_article_params)
      render json: @retrieved_article
    else
      render json: @retrieved_article.errors, status: :unprocessable_entity
    end
  end



  #----HTTP CALLS TO MAIN BLOG APP----#

  # GET Articles
  def index
    @retrieved_articles = RetrieveArticlesIndexRequest.retrieve_from_api
  end


  #POST Article
  def create_article
    response = CreateArticleRequest.send_request(article_params)
    if response.code  < 300
      render json: {status: "POST request completed. Response code: #{response}"}
    else
      render json: {error: "unable to process Article POST request to main app. Response code: #{response.code} "}, status: :bad_request
    end
  end


  #DELETE Article
  def destroy
    article_id = params[:article_id]
    author_key= params[:author_key]

    puts author_key
    puts article_id

    response = DestroyArticleRequest.send_request(article_id, author_key)
    puts "RISPOSTA:"
    puts response
    puts "!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"

    if response.code <= 300
      render json: {status: "POST request completed. Response code: #{response.code}"}
    else
      render json: {error: "unable to process Article DELETE request to main app. Response code: #{response.code} "}, status: :bad_request
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_retrieved_article
      @retrieved_article = RetrievedArticle.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def retrieved_article_params
      params.permit.fetch(:retrieved_article, {}).permit(:title, :body, :status, :author_id, :language)
    end

  def article_params
    params.permit(:title, :body, :status, :author_id, :language,  :authenticity_token, :commit, :author_key)
  end
end

app/views/retrieved_articles/_form.html.erb
<%= form_with(url: create_article_path) do |form| %>

  <%#try to avoid InvalidAuthenticityToken %>
  <%= hidden_field_tag :authenticity_token, form_authenticity_token %>

  <div>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </div>

  <div>
    <%= form.label :body %><br>
    <%= form.text_area :body %><br>
  </div>

  <div>
    <%= form.label :status %><br>
    <%= form.select :status, [["Public", "public"], ["Private", "private"], ["Archived", "archived"]], selected: 'public' %>
  </div>

  <div>
    <%= form.label :author_name, 'Choose Author' %><br>
    <%= form.select :author_id, [], { prompt: 'Select Author' }, id: 'author_select' %>
  </div>
  <%= form.hidden_field :author_key, id: 'key' %>

  <div>
    <%= form.label :language, "Choose Language" %>
    <%= form.select :language, [["English", "en"], ["Italian", "it"], ["Spanish", "es"]], selected: "en" %>
  </div>


  <div>
    <%= form.label :author_key %><br>
    <%= form.text_field :author_key %>
  </div>


  <div>
    <%= form.submit %>
  </div>
<% end %>




<%#this script is retrieving authors from the main app and displaying them a s a dropdown menu.
Rows' lables are author.name and the values passed are Author.id as author_id and Author.key as author_key%>
<script>
    document.addEventListener('DOMContentLoaded', () => {
        fetch('http://localhost:3000/authors')
            .then(response => response.json())
            .then(data => {
                console.log(data); // Log the data received from the server
                const authorSelect = document.getElementById('author_select');
                const keyInput = document.getElementById('key'); // Get the hidden key input
                if (authorSelect && keyInput) {
                    authorSelect.addEventListener('change', () => {
                        const selectedOption = authorSelect.options[authorSelect.selectedIndex];
                        keyInput.value = selectedOption.getAttribute('data-key'); // Update the key input value
                    });
                    data.authors.forEach(author => {
                        const option = document.createElement('option');
                        option.value = author.id;
                        option.setAttribute('data-key', author.key);
                        option.textContent = author.name;
                        authorSelect.appendChild(option);
                    });
                } else {
                    console.error('Author select dropdown or key input field not found');
                }
            })
            .catch(error => {
                console.error('Error fetching authors:', error);
            });
    });
</script>

app/views/retrieved_articles/index.html.erb
<!-- app/views/articles/index.html.erb -->
<!DOCTYPE html>
<html lang="">
<head>
  <title>Articles</title>
</head>

<body>

<style>
    .deletion-message {
        font-weight: bold;
        padding: 10px;
        margin: 10px 0;
    }

    .success {
        color: green;
    }

    .failure {
        color: red;
    }
</style>

<script>
  function ask_author_key(article_id) {

      let author_key = prompt("Enter your Key:", "Key...")

      if (author_key != null) {
          let requestURL = `/retrieved_articles/${article_id}`

          //make the AJAX request
          fetch(requestURL, {
              method: 'DELETE',
              headers: {
                  'Content-Type': 'application/json'
              },
              //passes the following arguments to controller:
              body: JSON.stringify({
                  article_id: article_id,
                  author_key: author_key
              })
          })
              .then(response => {
                  if (response.ok) {
                      displayDeletionResult(true)
                      console.log('Article deleted successfully');
                  } else {
                      displayDeletionResult(false)
                      console.error('Error deleting article');
                  }
              })
              .catch(error => {
                  console.error('Error:', error);
              });
      }
  }

  //write a message to the bottom of the page based on DELETE response
  function displayDeletionResult(result) {
      if (result===false) {
          // Create a div element to hold the message
          const deletionFailureMessage = document.createElement('div');
          deletionFailureMessage.textContent = 'Failed to delete article. Please try again later.';
          deletionFailureMessage.classList.add('failure'); // Add failure class
          deletionFailureMessage.classList.add('deletion-failure-message');

          // Append the message to the body of the document
          document.body.appendChild(deletionFailureMessage);
      }
      else {
          // Create a div element to hold the message
          const deletionDoneMessage = document.createElement('div');
          deletionDoneMessage.textContent = 'Article was destroyed successfully';
          deletionDoneMessage.classList.add('success'); // Add success class
          deletionDoneMessage.classList.add('deletion-done-message');

          // Append the message to the body of the document
          document.body.appendChild(deletionDoneMessage);
      }
  }
</script>


<h1>Articles</h1>
<ul>
  <% @retrieved_articles['articles'].each do |retrieved_article| %>
    <li>
      <!-- Display article -->
      <h2><%= retrieved_article['title'] %></h2>
      <p><%= retrieved_article['body'] %></p>
      <br></br>

      <%= hidden_field_tag "articles[][author_key]", "", id: "author_key_#{retrieved_article['id']}" %>

      <!-- Destroy article -->
      <button onClick="ask_author_key(<%=retrieved_article['id'] %>)">Delete Article</button>

    </li>
  <% end %>
</ul>

<!-- finestra di popup apparsa alla pressione del tasto Delete Article-->
<div id="popup" style="display: none">
  <p>hello</p>
</div>

</body>
</html>

<%= link_to "New Article", new_retrieved_article_path %>

app/views/retrieved_articles/new.html.erb
<h1>New Article</h1>

<%= render "form"%>